//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAOCONGNO
    {
        public int MaChiTietBaoCaoCongNo { get; set; }
        public Nullable<int> MaBaoCaoCongNo { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<decimal> NoDau { get; set; }
        public Nullable<decimal> NoPhatSinh { get; set; }
        public Nullable<decimal> NoCuoi { get; set; }
    
        public virtual BAOCAOCONGNO BAOCAOCONGNO { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
