//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAOTON
    {
        public int MaChiTietBaoCaoTon { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> MaBaoCaoTon { get; set; }
        public Nullable<int> TonDauKy { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
        public Nullable<int> TonCuoiKy { get; set; }
    
        public virtual BAOCAOTON BAOCAOTON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
