//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUDICHVU
    {
        public int MaChiTietPhieuDichVu { get; set; }
        public Nullable<int> MaPhieuDichVu { get; set; }
        public Nullable<int> MaDichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUDICHVU PHIEUDICHVU { get; set; }
    }
}
