//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUBANHANG
    {
        public int MaChiTietPhieuBanHang { get; set; }
        public Nullable<int> MaPhieuBanHang { get; set; }
        public int SoLuongBan { get; set; }
        public Nullable<decimal> DonGiaTien { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public int MaSanPham { get; set; }
    
        public virtual PHIEUBANHANG PHIEUBANHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
