//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHKHOANCHI
    {
        public DANHSACHKHOANCHI()
        {
            this.BAOCAODOANHTHUs = new HashSet<BAOCAODOANHTHU>();
            this.PHIEUCHIs = new HashSet<PHIEUCHI>();
            this.PHIEUHANGGIACONGs = new HashSet<PHIEUHANGGIACONG>();
            this.PHIEUMUAHANGs = new HashSet<PHIEUMUAHANG>();
        }
    
        public int MaDanhSachKhoanChi { get; set; }
        public Nullable<System.DateTime> NgayChi { get; set; }
        public Nullable<decimal> TienChiPhieuMuaHang { get; set; }
        public Nullable<decimal> TienChiPhieuHangGiaCong { get; set; }
        public Nullable<decimal> TienChiPhieuChi { get; set; }
        public Nullable<decimal> TongTienChi { get; set; }
    
        public virtual ICollection<BAOCAODOANHTHU> BAOCAODOANHTHUs { get; set; }
        public virtual ICollection<PHIEUCHI> PHIEUCHIs { get; set; }
        public virtual ICollection<PHIEUHANGGIACONG> PHIEUHANGGIACONGs { get; set; }
        public virtual ICollection<PHIEUMUAHANG> PHIEUMUAHANGs { get; set; }
    }
}
