//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHKHOANTHU
    {
        public DANHSACHKHOANTHU()
        {
            this.BAOCAODOANHTHUs = new HashSet<BAOCAODOANHTHU>();
            this.PHIEUBANHANGs = new HashSet<PHIEUBANHANG>();
            this.PHIEUDICHVUs = new HashSet<PHIEUDICHVU>();
        }
    
        public int MaDanhSachKhoanThu { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<int> TienThuPhieuBanHang { get; set; }
        public Nullable<int> TienThuPhieuDichVu { get; set; }
        public Nullable<decimal> TongTienThu { get; set; }
    
        public virtual ICollection<BAOCAODOANHTHU> BAOCAODOANHTHUs { get; set; }
        public virtual ICollection<PHIEUBANHANG> PHIEUBANHANGs { get; set; }
        public virtual ICollection<PHIEUDICHVU> PHIEUDICHVUs { get; set; }
    }
}
