//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGGIACONG
    {
        public HANGGIACONG()
        {
            this.CHITIETPHIEUHANGGIACONGs = new HashSet<CHITIETPHIEUHANGGIACONG>();
        }
    
        public int MaHangGiaCong { get; set; }
        public string TenHangGiaCong { get; set; }
        public Nullable<int> DonGiaGiaCong { get; set; }
    
        public virtual ICollection<CHITIETPHIEUHANGGIACONG> CHITIETPHIEUHANGGIACONGs { get; set; }
    }
}
