//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOANPHI
    {
        public KHOANPHI()
        {
            this.CHITIETPHIEUCHIs = new HashSet<CHITIETPHIEUCHI>();
        }
    
        public int MaKhoanPhi { get; set; }
        public string TenKhoanPhi { get; set; }
    
        public virtual ICollection<CHITIETPHIEUCHI> CHITIETPHIEUCHIs { get; set; }
    }
}
