//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBANHANG
    {
        public PHIEUBANHANG()
        {
            this.CHITIETPHIEUBANHANGs = new HashSet<CHITIETPHIEUBANHANG>();
            this.PHIEUNOes = new HashSet<PHIEUNO>();
        }
    
        public int MaPhieuBanHang { get; set; }
        public Nullable<int> MaDanhSachKhoanThu { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> TongCong { get; set; }
        public Nullable<decimal> SoTienThanhToan { get; set; }
        public Nullable<decimal> SoTienNo { get; set; }
    
        public virtual ICollection<CHITIETPHIEUBANHANG> CHITIETPHIEUBANHANGs { get; set; }
        public virtual DANHSACHKHOANTHU DANHSACHKHOANTHU { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<PHIEUNO> PHIEUNOes { get; set; }
    }
}
