//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUHANGGIACONG
    {
        public PHIEUHANGGIACONG()
        {
            this.CHITIETPHIEUHANGGIACONGs = new HashSet<CHITIETPHIEUHANGGIACONG>();
        }
    
        public int MaPhieuHangGiaCong { get; set; }
        public Nullable<int> MaDanhSachKhoanChi { get; set; }
        public Nullable<int> MaTho { get; set; }
        public Nullable<System.DateTime> NgayGiaCong { get; set; }
        public Nullable<System.DateTime> NgayNhanHangGiaCong { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> TongCong { get; set; }
    
        public virtual ICollection<CHITIETPHIEUHANGGIACONG> CHITIETPHIEUHANGGIACONGs { get; set; }
        public virtual DANHSACHKHOANCHI DANHSACHKHOANCHI { get; set; }
        public virtual THOGIACONG THOGIACONG { get; set; }
    }
}
