//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUAHANG
    {
        public PHIEUMUAHANG()
        {
            this.CHITIETPHIEUMUAHANGs = new HashSet<CHITIETPHIEUMUAHANG>();
        }
    
        public int MaPhieuMuaHang { get; set; }
        public Nullable<int> MaDanhSachKhoanChi { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> TongCong { get; set; }
    
        public virtual ICollection<CHITIETPHIEUMUAHANG> CHITIETPHIEUMUAHANGs { get; set; }
        public virtual DANHSACHKHOANCHI DANHSACHKHOANCHI { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
