//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHI
    {
        public PHIEUCHI()
        {
            this.CHITIETPHIEUCHIs = new HashSet<CHITIETPHIEUCHI>();
        }
    
        public int MaPhieuChi { get; set; }
        public Nullable<int> MaDanhSachKhoanChi { get; set; }
        public Nullable<System.DateTime> NgayChi { get; set; }
        public Nullable<decimal> TongCong { get; set; }
    
        public virtual ICollection<CHITIETPHIEUCHI> CHITIETPHIEUCHIs { get; set; }
        public virtual DANHSACHKHOANCHI DANHSACHKHOANCHI { get; set; }
    }
}
