//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNO
    {
        public int MaPhieuNo { get; set; }
        public Nullable<int> MaPhieuBanHang { get; set; }
        public Nullable<System.DateTime> NgayNo { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<decimal> SoTienTra { get; set; }
        public Nullable<decimal> TienConLai { get; set; }
    
        public virtual PHIEUBANHANG PHIEUBANHANG { get; set; }
    }
}
