//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETBAOCAOTONs = new HashSet<CHITIETBAOCAOTON>();
            this.CHITIETPHIEUBANHANGs = new HashSet<CHITIETPHIEUBANHANG>();
            this.CHITIETPHIEUMUAHANGs = new HashSet<CHITIETPHIEUMUAHANG>();
            this.CHITIETPHIEUNHAPKHOes = new HashSet<CHITIETPHIEUNHAPKHO>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MaLoaiSanPham { get; set; }
    
        public virtual ICollection<CHITIETBAOCAOTON> CHITIETBAOCAOTONs { get; set; }
        public virtual ICollection<CHITIETPHIEUBANHANG> CHITIETPHIEUBANHANGs { get; set; }
        public virtual ICollection<CHITIETPHIEUMUAHANG> CHITIETPHIEUMUAHANGs { get; set; }
        public virtual ICollection<CHITIETPHIEUNHAPKHO> CHITIETPHIEUNHAPKHOes { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
