//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOGIACONG
    {
        public THOGIACONG()
        {
            this.PHIEUHANGGIACONGs = new HashSet<PHIEUHANGGIACONG>();
        }
    
        public int MaTho { get; set; }
        public string TenTho { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<PHIEUHANGGIACONG> PHIEUHANGGIACONGs { get; set; }
    }
}
